version = "V3"
id = 0
featured = false
hash = "e90b5735a2fa0a585ad246ff71031d4831b858a364feed995d4913b27b709e59"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Easy"
authors = []
hash = "a87797f854804ed9f0973c61fc06da882f52ab4f675e8decaa2ca675c9633fc9"

[[levels]]
id = 0
name = "Hard"
hash = "74b0f2d01a658f9db94c753cc0c643ef7d08840797ad68d035a13133f93495b9"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
