version = "V3"
id = 0
featured = false
hash = "879172445537370b04f6ab7c754f811190531ad4bc451f9c8fd127a682507ab8"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Normal"
authors = []
hash = "949a6a93ddd6d1fdd36805d78309bddd6616634cc33caf3948049f4d157ed3c8"
