version = "V3"
id = 0
featured = false
hash = "608f2f19033a03bb7753beb55efaf6529f8678c22bf5fc219d4e99bb73e47d03"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Normal"
authors = []
hash = "181a05a9967de0b30c6479e147368dd217316440194035c6e03a1cb20bf6afea"
