version = "V3"
id = 0
featured = false
hash = "c82f5d8e02848069b2823ed46efd86ed0ac18ddc006960698d7b4c91b9d72bad"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Normal"
authors = []
hash = "0680ae59d0bbea82f1e9c27c7bc5a65d0c4f8d88f77fd8136caaecadc5725fad"
