version = "V3"
id = 0
featured = false
hash = "ec4626d22412541f3b4ff7086ac5c87cc322182ea43626d58728547f2dc4e25d"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Normal"
authors = []
hash = "8a896eaa07ebab008c4536f996eecca5bbfa6a6bb64f0a5567ccf46e0a76e819"
