version = "V3"
id = 0
featured = false
hash = "50173a8a10b3793b8c113567249afe4536b3c97bb63ae0e7d98a5fa14888aea7"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Easy"
authors = []
hash = "28b5e75c0b061ac97d48164551716327c1de7e810018fd01eb855fa473ed6fd0"

[[levels]]
id = 0
name = "Hard"
hash = "0fc7941a3aad1180ef36c2dcfc07590cf2a99ebeebd914a5297d476c10b14500"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
