version = "V3"
id = 4
featured = false
hash = "3e10410d072ae5caa0f9e52f351c0654a44712235a8f9c759655c3bd20909db9"

[music]
id = 4
original = false
featured = true
name = "Gonna Terraform It!"
romanized = "Gonna Terraform It!"

[[music.authors]]
id = 0
name = "typeyourtexthereblog"
romanized = "typeyourtexthereblog"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 11
name = "Easy"
hash = "512a98dca48471a65ff42471cc6c54f3b895e84b3d9126d4c4515730d08fc348"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 12
name = "Normal"
hash = "d39fc19bb689fbfd6f4bae6bdaa70537d9b2c50509987fae88eb06b1f4d708ed"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 13
name = "Hard"
hash = "f75370801a5b6d2e5e17d8f2af798e2d8d64f00d13a74166c94891fddaca81d1"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
