version = "V2"
id = 0
featured = false
hash = "a378c91545b38b747ac3d09045da4a723ee35ad914128c558237c43e50fdf672"

[music]
id = 0
original = false
featured = false
name = "trailer"
romanized = "trailer"

[[music.authors]]
id = 0
name = "IcyLava"
romanized = "IcyLava"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Hard"
authors = []
hash = "4d976bdb6112665424eb3eb48616e45b6a9f9421b9a20faf4a9023b4d64c2c59"
