version = "V3"
id = 0
featured = false
hash = "2cab33ccbe5922e25e9777894a7549a053cfefa39f768f639d4d43752f640179"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Hard"
hash = "9586052435f8395e57bb34c4507045bdb7a32b59fca143697235ed032e30ede3"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
