version = "V3"
id = 0
featured = false
hash = "f885a6c3ec81e6257ef4b97275a0d355bed06ee346756107fbea6823c5cfa56d"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Easy"
authors = []
hash = "8c2afc9acab8d257bf244213a81c56755e4911f2a31931d414df0d16c4d674ba"

[[levels]]
id = 0
name = "Hard"
hash = "9586052435f8395e57bb34c4507045bdb7a32b59fca143697235ed032e30ede3"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
