version = "V3"
id = 0
featured = false
hash = "317787c97f0553426f851bbf192d7a864004b34e18ee43410638434db7d82806"

[music]
id = 0
original = false
featured = true
name = "Show"
romanized = "Show"

[[music.authors]]
id = 0
name = "artyomzifir"
romanized = "artyomzifir"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 0
name = "Normal"
hash = "841dc3e650ce6df8ca40e9f59c243804066a9462e9ca413e326e0f3ed5809aa3"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
