version = "V3"
id = 3
featured = false
hash = "01000362c45bda06db03742e8f439325fbc859a5f2ffd66b207a3f03ee9a8b3d"

[music]
id = 3
original = false
featured = false
name = "Pixel Peeker Polka"
romanized = "Pixel Peeker Polka"

[[music.authors]]
id = 0
name = "Kevin MacLeod"
romanized = "Kevin MacLeod"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 7
name = "Easy"
hash = "68b06b821a5062cf833c0e84130ce7282f0d4edbe8ceef801f92166d36e98b4f"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"

[[levels]]
id = 8
name = "Normal"
hash = "3c59b3d2b452a2633649a840028f653cae2fb9fbf11d7883a5c4636bf086f96d"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"

[[levels]]
id = 9
name = "Hard"
hash = "e9b7dfa53705e74ad5286314d431322c212cbeec315ace7fb4db65350fa4f415"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"

[[levels]]
id = 10
name = "Insane"
hash = "786a218596473631bc3879dab7bd3a360f3c04c727e69d4e5fb9f73a0e8eda95"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"
