version = "V3"
id = 3
featured = false
hash = "23d04f25cdf460bf6d074e85500839b7c7cb719d8899b00dd337531a9cb0e387"

[music]
id = 3
original = false
featured = false
name = "Pixel Peeker Polka"
romanized = "Pixel Peeker Polka"

[[music.authors]]
id = 0
name = "Kevin MacLeod"
romanized = "Kevin MacLeod"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 7
name = "Easy"
hash = "c93b469bef1472b36a295aea3ba4abf194c4aac44ea18ac0969a168c6f059b31"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"

[[levels]]
id = 8
name = "Normal"
hash = "1b37dea0b04b82ffae89e7f02eeb9dbfaf290ccd90b869cda663770193f428b7"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"

[[levels]]
id = 9
name = "Hard"
hash = "1da661086511c08665bbdba663e335a6de192d6d578108f3f11b8acb86414f09"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"

[[levels]]
id = 10
name = "Insane"
hash = "aead27f9566b5889c2dd24dbbbfbb5b5bd9b083804f069a88929c185ed564d0d"

[[levels.authors]]
id = 0
name = "ricky-lee"
romanized = "ricky-lee"
