version = "V3"
id = 2
featured = false
hash = "d2268ceb539bb5d17e86a414025c4dca7527f30c1f1c19289ddcd9778ca11247"

[music]
id = 2
original = true
featured = true
name = "Rest"
romanized = "Rest"

[[music.authors]]
id = 0
name = "Nertsal"
romanized = "Nertsal"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 4
name = "Easy"
hash = "caf290d82fdb32cc8ccebef32351d3ca5d6585e072d4d06cca69b0687c456c7a"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 5
name = "Normal"
hash = "9f40c1916ff7eda51bfceba413bd4e020fdd3489893b232fe69ca45c589e9d0e"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 6
name = "Hard"
hash = "96e3c99636f0642de47deac52d7ef01ebfcedf4b271272e4835d39f4ff528dd2"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
