version = "V3"
id = 2
featured = false
hash = "825cd025af1b365645eb06a395d0d493a2bfe0083e4b853cf69834bad08ece85"

[music]
id = 2
original = true
featured = true
name = "Rest"
romanized = "Rest"

[[music.authors]]
id = 0
name = "Nertsal"
romanized = "Nertsal"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 4
name = "Easy"
hash = "43b2ee0d7bb504d21333a599ba7760042f0302dc319308ff3ae569cb333dd795"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 5
name = "Normal"
hash = "13a2234cb4dd853d5ebdfd53315718c6eeb17d657e3be9ea9d984d9ec6c246ec"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 6
name = "Hard"
hash = "82c01e9c4c1da3985718ee8213a7ee1ed7fd456198bf56644c5387586d1b0840"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
