version = "V3"
id = 4
featured = false
hash = "fae4ad20b3db4210cf8d735a25fd100003041daf0b2cb811617117a95f705c9d"

[music]
id = 4
original = false
featured = true
name = "Gonna Terraform It!"
romanized = "Gonna Terraform It!"

[[music.authors]]
id = 0
name = "typeyourtexthereblog"
romanized = "typeyourtexthereblog"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 11
name = "Easy"
hash = "4d4e4a406f05e631612539477fb2b007f35265d4891716813b70bf16d54f8efb"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 12
name = "Normal"
hash = "8591db6d84ca5fe03ecf0fc0ff7fc5009e2c818beafd063b62e7a6b7ff4f54e1"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 13
name = "Hard"
hash = "e2408851f18772f66565942d6d4699484e478b14f341ce690666a59969ba6aaa"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
