version = "V3"
id = 1
featured = false
hash = "240d5995b4aac04bf6a320603908e9c42c0c63f99b85795f414cb35286fa2691"

[music]
id = 1
original = true
featured = true
name = "Far from Dark"
romanized = "Far from Dark"

[[music.authors]]
id = 0
name = "IcyLava"
romanized = "IcyLava"

[owner]
id = 1
name = "Nertsal"

[[levels]]
id = 1
name = "Easy"
hash = "a066f51638a985811e19bce245cec1b63e65baaddf28f2deb4e55bbd481c79df"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"

[[levels]]
id = 2
name = "Normal"
hash = "74f17ef63893e9594109f835942658e60e9db2741ed702fef91369a4e4755511"

[[levels.authors]]
id = 0
name = "IcyLava"
romanized = "IcyLava"

[[levels]]
id = 3
name = "Hard"
hash = "63924d57c14c250b95d2d634588a81fba17803524467e3ec91686577f22ba373"

[[levels.authors]]
id = 1
name = "Nertsal"
romanized = "Nertsal"
